databases:
  - name: e_learning_db
    databaseName: e_learning_db
    user: django_user
    region: singapore
    plan: starter
 


services:
  - type: web
    name: e_learning
    env: python
    region: singapore
    plan: starter
    branch: master
    healthCheckPath: /
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: e_learning_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: false
    