# Generated by Django 3.2.6 on 2022-06-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='already_save',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
