# Generated by Django 3.2.6 on 2023-02-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobplace', '0002_taskmodel_already_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registormodel',
            name='exam_count',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
